import { LucideIcon, Book, BookOpen, BookOpenCheck, GraduationCap, School, NotebookPen, PenTool, Pencil, Calculator, BrainCircuit, Atom, Binary, FileSpreadsheet, FileText, FlaskConical, Globe2, Languages, LanguagesIcon, Library, Lightbulb, Microscope, Music2, Palette, Pi, Puzzle, ScrollText, Speech, Trophy, Upload, Users, Video } from "lucide-react";

export const EDUCATION_ICONS: { [key: string]: LucideIcon } = {
    Book,
    BookOpen,
    BookOpenCheck,
    GraduationCap,
    School,
    NotebookPen,
    PenTool,
    Pencil,
    Calculator,
    BrainCircuit,
    Atom,
    Binary,
    FileSpreadsheet,
    FileText,
    FlaskConical,
    Globe2,
    Languages,
    LanguagesIcon,
    Library,
    Lightbulb,
    Microscope,
    Music2,
    Palette,
    Pi,
    Puzzle,
    ScrollText,
    Speech,
    Trophy,
    Upload,
    Users,
    Video,
  };